# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ATE_IF_WBS <- function(Z, event, time, t, beta, index_A, trunc_time_init = NULL, cause = 1L, IF = TRUE, WBS = TRUE, bs_iter = 1e4L, level = 0.95, arms = FALSE) {
    .Call(`_ATESurvival_ATE_IF_WBS`, Z, event, time, t, beta, index_A, trunc_time_init, cause, IF, WBS, bs_iter, level, arms)
}

EBS <- function(Z, event, time, t, beta, index_A, factor_init = NULL, trunc_time_init = NULL, cause = 1L) {
    .Call(`_ATESurvival_EBS`, Z, event, time, t, beta, index_A, factor_init, trunc_time_init, cause)
}

